### PR TITLE
Add first draft of standalone automatically validable benchmarks.

### PR DESCRIPTION
**Pull request by jmirabel**
As of now, there is (*almost*) no validation done. The C++ benchmarks are independent of CORBA so:
- they give good examples of how to use HPP in C++,
- they are easy to run in any CI / script (just run the generated executable `benchmarks`).

As a side note, I find it fairly easy to play with HPP in C++. I never really tried before. This is biased by the fact that I know the API, of course...

@nim65s we would like to keep track of the evolution of the different metrics each benchmark has. Do you know a nice way of doing this ? something like CDash ?

### CODE REVIEW

**Comment by jmirabel** [comment]
> @nim65s we would like to keep track of the evolution of the different metrics each benchmark has. Do you know a nice way of doing this ? something like CDash ?

One simple way is to create one or several doxygen pages, with plots generates from the benchmark results. This should be easy to do. Then, all we have to do is to publish hpp_benchmark documentation, and @nim65s already know how to do this easily.
@nim65s would you agree with this ?

**Comment by nim65s** [comment]
Than can be interesting, and can be added on my todo list, but I don't know how much time this would need.

**Comment by jmirabel** [comment]
My question was more on how (what tool, ...) than on who.

**Comment by jmirabel** [comment]
I am now satisfied with this. @nim65s to publish the benchmark results, you only have to publish the doxygen documentation. I am sure you know how to do this if it is not already done.

Note that if you run `make doc` now, you may have an error because there is no C++ benchmark.

I have added instructions on how to launch the C++ and Python benchmarks. I am sure of the C++ part and almost sure of the Python part. Conversely to what one would expect, the C++ part is very easy to script while the Python part is a little harder.

The next step is to provide procedure to validate automatically the output.

**Pull request merged**
